// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7hmPsmimDkhkCNtfIaAN_f7QttxYW59s',
    appId: '1:868713228878:web:0679dfbd1ad14c37c9f11f',
    messagingSenderId: '868713228878',
    projectId: 'flutterfirebaseapp-f59f3',
    authDomain: 'flutterfirebaseapp-f59f3.firebaseapp.com',
    storageBucket: 'flutterfirebaseapp-f59f3.appspot.com',
    measurementId: 'G-H04S8EYTV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9WknOjwYJ3oDSpxY-jimA11Xg3YxuMxo',
    appId: '1:868713228878:android:41ea823f64d83369c9f11f',
    messagingSenderId: '868713228878',
    projectId: 'flutterfirebaseapp-f59f3',
    storageBucket: 'flutterfirebaseapp-f59f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzObjDOW-3glkhrC-hyYjGOIITlCqcx7U',
    appId: '1:868713228878:ios:512c71c7f91f5c94c9f11f',
    messagingSenderId: '868713228878',
    projectId: 'flutterfirebaseapp-f59f3',
    storageBucket: 'flutterfirebaseapp-f59f3.appspot.com',
    iosClientId: '868713228878-idmiqv0egjvqlk09e8ubbi038gt2hmsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzObjDOW-3glkhrC-hyYjGOIITlCqcx7U',
    appId: '1:868713228878:ios:c7cec97e00a9ee38c9f11f',
    messagingSenderId: '868713228878',
    projectId: 'flutterfirebaseapp-f59f3',
    storageBucket: 'flutterfirebaseapp-f59f3.appspot.com',
    iosClientId: '868713228878-rc8baqtacdstcrs4itrooiiqdkeq8eiu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp.RunnerTests',
  );
}
